onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - lefthook
  - maplibre-gl
  - prisma
  - puppeteer
  - sharp
  - vue-demi
  - workerd
